name: ti_sdk_npm

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12 
      - run: npm install
      - run: npm test    
      - run: npm run build
      - run: ls -al
      - run: ls -al dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/ 
      - name: Setup GIT
        run: |
          git config user.email "developer@touchlessinteractive.app"
          git config user.name "touchlessinteractive"
      - run : npm version patch 
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
